# Form implementation generated from reading ui file 'OCR.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide6.QtWidgets import *

class Ui_OCR(object):
    def setupUi(self, OCR):
        OCR.setObjectName("OCR")
        OCR.resize(500, 450)
        self.centralwidget = QtWidgets.QWidget(parent=OCR)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 450))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:#14213d;\n"
"    border:6px solid #FFDB70;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.persian_rdbtn = QtWidgets.QRadioButton(parent=self.frame)
        self.persian_rdbtn.setGeometry(QtCore.QRect(280, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.persian_rdbtn.setFont(font)
        self.persian_rdbtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.persian_rdbtn.setStyleSheet("QRadioButton{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked{\n"
"width:15px;\n"
"height:15px;\n"
"  border-radius:7px;    \n"
"    background-color: qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator::unchecked {\n"
"width:12px;\n"
"height:12px;\n"
"  border-radius:7px;\n"
"    border:2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;\n"
"    background-color: none;\n"
"\n"
"}")
        self.persian_rdbtn.setObjectName("persian_rdbtn")
        self.createtxt_btn = QtWidgets.QPushButton(parent=self.frame)
        self.createtxt_btn.setGeometry(QtCore.QRect(190, 330, 100, 51))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.createtxt_btn.setFont(font)
        self.createtxt_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createtxt_btn.setStyleSheet("QPushButton{\n"
"border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"border-radius:20px;\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;   \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(167, 167, 167);\n"
"border:none;\n"
"    color:#14213d;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.createtxt_btn.setIcon(icon)
        self.createtxt_btn.setIconSize(QtCore.QSize(25, 25))
        self.createtxt_btn.setObjectName("createtxt_btn")
        self.chooseimage_btn = QtWidgets.QPushButton(parent=self.frame)
        self.chooseimage_btn.setGeometry(QtCore.QRect(190, 110, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.chooseimage_btn.setFont(font)
        self.chooseimage_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.chooseimage_btn.setStyleSheet("QPushButton{\n"
"border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"border-radius:20px;\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;   \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(167, 167, 167);\n"
"border:none;\n"
"    color:#14213d;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\chooseImage.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.chooseimage_btn.setIcon(icon1)
        self.chooseimage_btn.setIconSize(QtCore.QSize(25, 25))
        self.chooseimage_btn.setObjectName("chooseimage_btn")
        self.english_rdbtn = QtWidgets.QRadioButton(parent=self.frame)
        self.english_rdbtn.setGeometry(QtCore.QRect(150, 70, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.english_rdbtn.setFont(font)
        self.english_rdbtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.english_rdbtn.setStyleSheet("QRadioButton{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked{\n"
"width:15px;\n"
"height:15px;\n"
"  border-radius:7px;    \n"
"    background-color: qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator::unchecked {\n"
"width:12px;\n"
"height:12px;\n"
"  border-radius:7px;\n"
"    border:2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;\n"
"    background-color: none;\n"
"\n"
"}")
        self.english_rdbtn.setChecked(True)
        self.english_rdbtn.setObjectName("english_rdbtn")
        self.Title = QtWidgets.QLabel(parent=self.frame)
        self.Title.setGeometry(QtCore.QRect(32, 18, 231, 31))
        font = QtGui.QFont()
        font.setFamily("A Salamat")
        font.setPointSize(10)
        font.setBold(False)
        font.setKerning(True)
        self.Title.setFont(font)
        self.Title.setStyleSheet("\n"
"color: #a7a7a7;\n"
"border:none;")
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.ExitButton = QtWidgets.QPushButton(parent=self.frame)
        self.ExitButton.setGeometry(QtCore.QRect(455, 20, 25, 25))
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ExitButton.setStyleSheet("")
        self.ExitButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ExitButton.setIcon(icon2)
        self.ExitButton.setIconSize(QtCore.QSize(20, 20))
        self.ExitButton.setFlat(True)
        self.ExitButton.setObjectName("ExitButton")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(180, 400, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame)
        self.textEdit.setGeometry(QtCore.QRect(20, 170, 461, 151))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.textEdit.setStyleSheet("border:1px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;\n"
"color: rgb(255, 255, 255);\n"
"padding:10px;\n"
"\n"
"")
        self.textEdit.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textEdit.setReadOnly(True)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setObjectName("textEdit")
        OCR.setCentralWidget(self.centralwidget)

        self.retranslateUi(OCR)
        QtCore.QMetaObject.connectSlotsByName(OCR)

    def retranslateUi(self, OCR):
        _translate = QtCore.QCoreApplication.translate
        OCR.setWindowTitle(_translate("OCR", "MainWindow"))
        self.persian_rdbtn.setText(_translate("OCR", "فارسی"))
        self.createtxt_btn.setText(_translate("OCR", "ذخیره فایل"))
        self.chooseimage_btn.setText(_translate("OCR", "انتخاب عکس"))
        self.english_rdbtn.setText(_translate("OCR", "انگلیسی"))
        self.Title.setText(_translate("OCR", "Toolbox <span style=\" font-size:11pt; font-weight:600;\">-</span> OCR"))
        self.label.setText(_translate("OCR", "ذخیره شد"))
        self.textEdit.setHtml(_translate("OCR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gandom\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
