# Form implementation generated from reading ui file 'PasswordGenerator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#14213d;\n"
"    border:6px solid #FFDB70;\n"
"\n"
"border-radius:15px;\n"
"\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btn_refresh = QtWidgets.QPushButton(parent=self.frame)
        self.btn_refresh.setGeometry(QtCore.QRect(420, 180, 58, 54))
        self.btn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refresh.setStyleSheet("QPushButton {\n"
"    margin-right: 0;\n"
"    background-color: rgb(20, 33, 61);\n"
"    margin-left: 0;\n"
"}\n"
"")
        self.btn_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btn_refresh.setIcon(icon)
        self.btn_refresh.setIconSize(QtCore.QSize(52, 52))
        self.btn_refresh.setObjectName("btn_refresh")
        self.label_strength = QtWidgets.QLabel(parent=self.frame)
        self.label_strength.setGeometry(QtCore.QRect(60, 270, 261, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_strength.sizePolicy().hasHeightForWidth())
        self.label_strength.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(16)
        font.setKerning(True)
        self.label_strength.setFont(font)
        self.label_strength.setStyleSheet("padding-left:10px;\n"
"color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_strength.setText("")
        self.label_strength.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_strength.setObjectName("label_strength")
        self.btn_special = QtWidgets.QPushButton(parent=self.frame)
        self.btn_special.setGeometry(QtCore.QRect(440, 390, 95, 50))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(16)
        self.btn_special.setFont(font)
        self.btn_special.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_special.setStyleSheet("QPushButton{\n"
"\n"
"border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"border-radius:10px;\n"
"color: white; \n"
"    background-color:transparent;    \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;\n"
"}")
        self.btn_special.setCheckable(True)
        self.btn_special.setChecked(True)
        self.btn_special.setObjectName("btn_special")
        self.slider_length = QtWidgets.QSlider(parent=self.frame)
        self.slider_length.setGeometry(QtCore.QRect(50, 340, 411, 22))
        self.slider_length.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.slider_length.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: transparent;\n"
"    height: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: white;\n"
"    width: 22px;\n"
"    border-radius: 10px;\n"
"    margin-top: -8px;\n"
"    margin-bottom: -8px;\n"
"}\n"
"")
        self.slider_length.setMaximum(100)
        self.slider_length.setProperty("value", 12)
        self.slider_length.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_length.setObjectName("slider_length")
        self.btn_digits = QtWidgets.QPushButton(parent=self.frame)
        self.btn_digits.setGeometry(QtCore.QRect(308, 390, 95, 50))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(16)
        self.btn_digits.setFont(font)
        self.btn_digits.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_digits.setStyleSheet("QPushButton{\n"
"\n"
"border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"border-radius:10px;\n"
"color: white; \n"
"    background-color:transparent;    \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;\n"
"}")
        self.btn_digits.setCheckable(True)
        self.btn_digits.setChecked(False)
        self.btn_digits.setObjectName("btn_digits")
        self.spinbox_length = QtWidgets.QSpinBox(parent=self.frame)
        self.spinbox_length.setGeometry(QtCore.QRect(470, 330, 80, 41))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        
        self.spinbox_length.setFont(font)
        self.spinbox_length.setStyleSheet("QSpinBox {\n"
"    font: 14pt \"Gandom\";    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    background: transparent;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border-color: qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;\n"
"}\n"
"")
        self.spinbox_length.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinbox_length.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinbox_length.setMaximum(100)
        self.spinbox_length.setProperty("value", 12)
        self.spinbox_length.setObjectName("spinbox_length")
        self.btn_upper = QtWidgets.QPushButton(parent=self.frame)
        self.btn_upper.setGeometry(QtCore.QRect(176, 390, 95, 50))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(16)
        self.btn_upper.setFont(font)
        self.btn_upper.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_upper.setStyleSheet("QPushButton{\n"
"\n"
"border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"border-radius:10px;\n"
"color: white; \n"
"    background-color:transparent;    \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;\n"
"}")
        self.btn_upper.setCheckable(True)
        self.btn_upper.setChecked(False)
        self.btn_upper.setObjectName("btn_upper")
        self.frame_password = QtWidgets.QFrame(parent=self.frame)
        self.frame_password.setGeometry(QtCore.QRect(50, 180, 361, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_password.sizePolicy().hasHeightForWidth())
        self.frame_password.setSizePolicy(sizePolicy)
        self.frame_password.setStyleSheet("QFrame {\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;\n"
"    border-radius: 5px;\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    border-color: #FFDB70;\n"
"}\n"
"")
        self.frame_password.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_password.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_password.setObjectName("frame_password")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_password)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.line_password = QtWidgets.QLineEdit(parent=self.frame_password)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_password.setFont(font)
        self.line_password.setStyleSheet("QLineEdit {\n"
"    border-radius:5px;\n"
"    margin: 0;\n"
"    font-size: 16pt;\n"
"padding-left:6px;\n"
"padding-right:6px;\n"
"}\n"
"")
        self.line_password.setObjectName("line_password")
        self.horizontalLayout_10.addWidget(self.line_password)
        self.btn_visibility = QtWidgets.QPushButton(parent=self.frame_password)
        self.btn_visibility.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_visibility.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    margin: 0;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.btn_visibility.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\Project\Final\ToolBox\Images\invisible.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\visible.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btn_visibility.setIcon(icon1)
        self.btn_visibility.setIconSize(QtCore.QSize(30, 30))
        self.btn_visibility.setCheckable(True)
        self.btn_visibility.setChecked(True)
        self.btn_visibility.setObjectName("btn_visibility")
        self.horizontalLayout_10.addWidget(self.btn_visibility)
        self.btn_lower = QtWidgets.QPushButton(parent=self.frame)
        self.btn_lower.setGeometry(QtCore.QRect(44, 390, 95, 50))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(16)
        self.btn_lower.setFont(font)
        self.btn_lower.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_lower.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_lower.setStyleSheet("QPushButton{\n"
"\n"
"border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"border-radius:10px;\n"
"color: white; \n"
"    background-color:transparent;    \n"
"}\n"
"\n"
"QPushButton:checked {\n"
" background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;\n"
"}")
        self.btn_lower.setCheckable(True)
        self.btn_lower.setChecked(False)
        self.btn_lower.setObjectName("btn_lower")
        self.btn_copy = QtWidgets.QPushButton(parent=self.frame)
        self.btn_copy.setGeometry(QtCore.QRect(490, 180, 58, 54))
        self.btn_copy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_copy.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    background-color: rgb(20, 33, 61);\n"
"    margin-left: 0;\n"
"}\n"
"")
        self.btn_copy.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\Project\Final\ToolBox\Images\copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.btn_copy.setIcon(icon2)
        self.btn_copy.setIconSize(QtCore.QSize(42, 42))
        self.btn_copy.setObjectName("btn_copy")
        self.Title = QtWidgets.QLabel(parent=self.frame)
        self.Title.setGeometry(QtCore.QRect(32, 18, 231, 31))
        font = QtGui.QFont()
        font.setFamily("A Salamat")
        font.setPointSize(10)
        font.setBold(False)
        
        font.setKerning(True)
        self.Title.setFont(font)
        self.Title.setStyleSheet("\n"
"color: #a7a7a7;\n"
"border:none;")
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.ExitButton = QtWidgets.QPushButton(parent=self.frame)
        self.ExitButton.setGeometry(QtCore.QRect(550, 20, 25, 25))
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ExitButton.setStyleSheet("")
        self.ExitButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\Project\Final\ToolBox\Images\Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ExitButton.setIcon(icon3)
        self.ExitButton.setIconSize(QtCore.QSize(20, 20))
        self.ExitButton.setFlat(True)
        self.ExitButton.setObjectName("ExitButton")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(200, 50, 181, 101))
        self.pushButton.setStyleSheet("\n"
"background-color: rgb(20, 33, 61);")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\Project\Final\ToolBox\Images\pass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(300, 300))
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_refresh.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.btn_special.setText(_translate("MainWindow", "#$%"))
        self.btn_digits.setText(_translate("MainWindow", "0-9"))
        self.btn_upper.setText(_translate("MainWindow", "A-Z"))
        self.btn_lower.setText(_translate("MainWindow", "a-z"))
        self.btn_copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.Title.setText(_translate("MainWindow", "Toolbox <span style=\" font-size:11pt; font-weight:600;\">-</span> Password Generator"))
