# Form implementation generated from reading ui file 'QrCode.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 300))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:#14213d;\n"
"    border:6px solid #FFDB70;\n"
"border-radius:15px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btnshow = QtWidgets.QPushButton(parent=self.frame)
        self.btnshow.setGeometry(QtCore.QRect(270, 180, 100, 42))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.btnshow.setFont(font)
        self.btnshow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnshow.setStyleSheet("QPushButton{\n"
"\n"
"border-radius:10px;\n"
"\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;\n"
"}")
        self.btnshow.setObjectName("btnshow")
        self.savebtn = QtWidgets.QPushButton(parent=self.frame)
        self.savebtn.setGeometry(QtCore.QRect(130, 180, 100, 42))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.savebtn.setFont(font)
        self.savebtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.savebtn.setStyleSheet("QPushButton{\n"
"\n"
"border-radius:10px;\n"
"\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;\n"
"}")
        self.savebtn.setObjectName("savebtn")
        self.txtUrl = QtWidgets.QLineEdit(parent=self.frame)
        self.txtUrl.setGeometry(QtCore.QRect(80, 105, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.txtUrl.setFont(font)
        self.txtUrl.setStyleSheet("QLineEdit {\n"
"    border-radius:5px;\n"
"    margin: 0;\n"
"padding-left:6px;\n"
"padding-right:6px;\n"
"}\n"
"")
        self.txtUrl.setObjectName("txtUrl")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(280, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"color: qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));")
        self.label.setObjectName("label")
        self.ExitButton = QtWidgets.QPushButton(parent=self.frame)
        self.ExitButton.setGeometry(QtCore.QRect(455, 20, 25, 25))
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ExitButton.setStyleSheet("")
        self.ExitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ExitButton.setIcon(icon)
        self.ExitButton.setIconSize(QtCore.QSize(20, 20))
        self.ExitButton.setFlat(True)
        self.ExitButton.setObjectName("ExitButton")
        self.Title = QtWidgets.QLabel(parent=self.frame)
        self.Title.setGeometry(QtCore.QRect(32, 18, 231, 31))
        font = QtGui.QFont()
        font.setFamily("A Salamat")
        font.setPointSize(10)
        font.setBold(False)
        
        font.setKerning(True)
        self.Title.setFont(font)
        self.Title.setStyleSheet("\n"
"color: #a7a7a7;\n"
"border:none;")
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 243, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:none;\n"
"color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.btnshow.raise_()
        self.savebtn.raise_()
        self.txtUrl.raise_()
        self.ExitButton.raise_()
        self.Title.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnshow.setText(_translate("MainWindow", "نمایش بارکد"))
        self.savebtn.setText(_translate("MainWindow", "ذخیره بارکد"))
        self.label.setText(_translate("MainWindow", "لینک / متن :"))
        self.Title.setText(_translate("MainWindow", "Toolbox <span style=\" font-size:11pt; font-weight:600;\">-</span> Qr Code"))
        self.label_2.setText(_translate("MainWindow", "فایل ذخیره شد"))
