# Form implementation generated from reading ui file 'Weather.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:#14213d;\n"
"    border:6px solid #FFDB70;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QLabel{\n"
"color: rgb(249, 237, 78);\n"
"border:none\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(390, 120, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.searchBtn = QtWidgets.QPushButton(parent=self.frame)
        self.searchBtn.setGeometry(QtCore.QRect(140, 117, 40, 32))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.searchBtn.setFont(font)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.searchBtn.setStyleSheet("QPushButton{\n"
"\n"
"border: 2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"border-radius:10px;\n"
"background-color:qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"color: black;   \n"
"}\n"
"")
        self.searchBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchBtn.setIcon(icon)
        self.searchBtn.setIconSize(QtCore.QSize(25, 25))
        self.searchBtn.setCheckable(False)
        self.searchBtn.setFlat(True)
        self.searchBtn.setObjectName("searchBtn")
        self.CityNametxt = QtWidgets.QLineEdit(parent=self.frame)
        self.CityNametxt.setGeometry(QtCore.QRect(190, 117, 200, 32))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.CityNametxt.setFont(font)
        self.CityNametxt.setStyleSheet("border-radius:5px;\n"
"color: rgb(0, 0, 0);\n"
"padding-left:8px;\n"
"\n"
"padding-right:6px;")
        self.CityNametxt.setObjectName("CityNametxt")
        self.framePersian = QtWidgets.QFrame(parent=self.frame)
        self.framePersian.setGeometry(QtCore.QRect(15, 150, 571, 331))
        self.framePersian.setStyleSheet("border:none;")
        self.framePersian.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.framePersian.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.framePersian.setObjectName("framePersian")
        self.label_6 = QtWidgets.QLabel(parent=self.framePersian)
        self.label_6.setGeometry(QtCore.QRect(430, 270, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(parent=self.framePersian)
        self.label_3.setGeometry(QtCore.QRect(430, 90, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.framePersian)
        self.label_4.setGeometry(QtCore.QRect(430, 150, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.framePersian)
        self.label_5.setGeometry(QtCore.QRect(430, 210, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(parent=self.framePersian)
        self.label_2.setGeometry(QtCore.QRect(430, 30, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.WindLBL = QtWidgets.QLabel(parent=self.framePersian)
        self.WindLBL.setGeometry(QtCore.QRect(30, 210, 360, 20))
        self.WindLBL.setStyleSheet("color: rgb(255, 255, 255);")
        self.WindLBL.setText("")
        self.WindLBL.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.WindLBL.setObjectName("WindLBL")
        self.CityLBL = QtWidgets.QLabel(parent=self.framePersian)
        self.CityLBL.setGeometry(QtCore.QRect(30, 30, 360, 20))
        self.CityLBL.setStyleSheet("color: rgb(255, 255, 255);")
        self.CityLBL.setText("")
        self.CityLBL.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.CityLBL.setObjectName("CityLBL")
        self.WeatherTypeLBL = QtWidgets.QLabel(parent=self.framePersian)
        self.WeatherTypeLBL.setGeometry(QtCore.QRect(30, 90, 360, 20))
        self.WeatherTypeLBL.setStyleSheet("color: rgb(255, 255, 255);")
        self.WeatherTypeLBL.setText("")
        self.WeatherTypeLBL.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.WeatherTypeLBL.setObjectName("WeatherTypeLBL")
        self.SunsetLBL = QtWidgets.QLabel(parent=self.framePersian)
        self.SunsetLBL.setGeometry(QtCore.QRect(30, 270, 360, 21))
        self.SunsetLBL.setStyleSheet("color: rgb(255, 255, 255);")
        self.SunsetLBL.setText("")
        self.SunsetLBL.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.SunsetLBL.setObjectName("SunsetLBL")
        self.TempLBL = QtWidgets.QLabel(parent=self.framePersian)
        self.TempLBL.setGeometry(QtCore.QRect(30, 150, 360, 20))
        self.TempLBL.setStyleSheet("color: rgb(255, 255, 255);")
        self.TempLBL.setText("")
        self.TempLBL.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TempLBL.setObjectName("TempLBL")
        self.Title = QtWidgets.QLabel(parent=self.frame)
        self.Title.setGeometry(QtCore.QRect(32, 18, 231, 31))
        font = QtGui.QFont()
        font.setFamily("A Salamat")
        font.setPointSize(10)
        font.setBold(False)
        
        font.setKerning(True)
        self.Title.setFont(font)
        self.Title.setStyleSheet("\n"
"color: #a7a7a7;\n"
"border:none;")
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.ExitButton = QtWidgets.QPushButton(parent=self.frame)
        self.ExitButton.setGeometry(QtCore.QRect(552, 20, 25, 25))
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ExitButton.setStyleSheet("")
        self.ExitButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"D:\Project\Final\ToolBox\Images\Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ExitButton.setIcon(icon1)
        self.ExitButton.setIconSize(QtCore.QSize(20, 20))
        self.ExitButton.setFlat(True)
        self.ExitButton.setObjectName("ExitButton")
        self.frameEnglish = QtWidgets.QFrame(parent=self.frame)
        self.frameEnglish.setGeometry(QtCore.QRect(15, 150, 571, 331))
        self.frameEnglish.setStyleSheet("border:none;")
        self.frameEnglish.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameEnglish.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameEnglish.setObjectName("frameEnglish")
        self.label_7 = QtWidgets.QLabel(parent=self.frameEnglish)
        self.label_7.setGeometry(QtCore.QRect(30, 270, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frameEnglish)
        self.label_8.setGeometry(QtCore.QRect(30, 90, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frameEnglish)
        self.label_9.setGeometry(QtCore.QRect(30, 150, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frameEnglish)
        self.label_10.setGeometry(QtCore.QRect(30, 210, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frameEnglish)
        self.label_11.setGeometry(QtCore.QRect(30, 30, 105, 25))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.WindLBL_en = QtWidgets.QLabel(parent=self.frameEnglish)
        self.WindLBL_en.setGeometry(QtCore.QRect(170, 210, 360, 20))
        self.WindLBL_en.setStyleSheet("color: rgb(255, 255, 255);")
        self.WindLBL_en.setText("")
        self.WindLBL_en.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.WindLBL_en.setObjectName("WindLBL_en")
        self.CityLBL_en = QtWidgets.QLabel(parent=self.frameEnglish)
        self.CityLBL_en.setGeometry(QtCore.QRect(170, 30, 360, 20))
        self.CityLBL_en.setStyleSheet("color: rgb(255, 255, 255);")
        self.CityLBL_en.setText("")
        self.CityLBL_en.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.CityLBL_en.setObjectName("CityLBL_en")
        self.WeatherTypeLBL_en = QtWidgets.QLabel(parent=self.frameEnglish)
        self.WeatherTypeLBL_en.setGeometry(QtCore.QRect(170, 90, 360, 20))
        self.WeatherTypeLBL_en.setStyleSheet("color: rgb(255, 255, 255);")
        self.WeatherTypeLBL_en.setText("")
        self.WeatherTypeLBL_en.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.WeatherTypeLBL_en.setObjectName("WeatherTypeLBL_en")
        self.SunsetLBL_en = QtWidgets.QLabel(parent=self.frameEnglish)
        self.SunsetLBL_en.setGeometry(QtCore.QRect(170, 270, 360, 21))
        self.SunsetLBL_en.setStyleSheet("color: rgb(255, 255, 255);")
        self.SunsetLBL_en.setText("")
        self.SunsetLBL_en.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.SunsetLBL_en.setObjectName("SunsetLBL_en")
        self.TempLBL_en = QtWidgets.QLabel(parent=self.frameEnglish)
        self.TempLBL_en.setGeometry(QtCore.QRect(170, 150, 360, 20))
        self.TempLBL_en.setStyleSheet("color: rgb(255, 255, 255);")
        self.TempLBL_en.setText("")
        self.TempLBL_en.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TempLBL_en.setObjectName("TempLBL_en")
        self.persian_rdbtn = QtWidgets.QRadioButton(parent=self.frame)
        self.persian_rdbtn.setGeometry(QtCore.QRect(320, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.persian_rdbtn.setFont(font)
        self.persian_rdbtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.persian_rdbtn.setStyleSheet("QRadioButton{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked{\n"
"width:15px;\n"
"height:15px;\n"
"  border-radius:7px;    \n"
"    background-color: qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator::unchecked {\n"
"width:12px;\n"
"height:12px;\n"
"  border-radius:7px;\n"
"    border:2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;\n"
"    background-color: none;\n"
"\n"
"}")
        self.persian_rdbtn.setObjectName("persian_rdbtn")
        self.english_rdbtn = QtWidgets.QRadioButton(parent=self.frame)
        self.english_rdbtn.setGeometry(QtCore.QRect(190, 70, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Gandom")
        font.setPointSize(10)
        self.english_rdbtn.setFont(font)
        self.english_rdbtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.english_rdbtn.setStyleSheet("QRadioButton{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked{\n"
"width:15px;\n"
"height:15px;\n"
"  border-radius:7px;    \n"
"    background-color: qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator::unchecked {\n"
"width:12px;\n"
"height:12px;\n"
"  border-radius:7px;\n"
"    border:2px solid qlineargradient(spread:pad, x1:0.006, y1:0.585, x2:1, y2:0, stop:0.369318 rgba(246, 176, 66, 255), stop:1 rgba(249, 237, 78, 255));;\n"
"    background-color: none;\n"
"\n"
"}")
        self.english_rdbtn.setChecked(True)
        self.english_rdbtn.setObjectName("english_rdbtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "نام شهر"))
        self.label_6.setText(_translate("MainWindow", "غروب خورشید"))
        self.label_3.setText(_translate("MainWindow", "وضعیت"))
        self.label_4.setText(_translate("MainWindow", "دما"))
        self.label_5.setText(_translate("MainWindow", "سرعت باد"))
        self.label_2.setText(_translate("MainWindow", "نام شهر"))
        self.Title.setText(_translate("MainWindow", "Toolbox <span style=\" font-size:11pt; font-weight:600;\">-</span> Weather"))
        self.label_7.setText(_translate("MainWindow", "Sunset:"))
        self.label_8.setText(_translate("MainWindow", "Status:"))
        self.label_9.setText(_translate("MainWindow", "Temperature:"))
        self.label_10.setText(_translate("MainWindow", "Wind speed:"))
        self.label_11.setText(_translate("MainWindow", "City Name:"))
        self.persian_rdbtn.setText(_translate("MainWindow", "فارسی"))
        self.english_rdbtn.setText(_translate("MainWindow", "English"))
